apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: "Force=true,Replace=true"
spec:
  project: default
  source:
    repoURL: https://github.com/Olyakaya/task_gitops.git
    targetRevision: main
    path: base # Use k8s/overlays/dev for development
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
