apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myappv1
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Force=true
spec:
  project: default
  source:
    repoURL: https://github.com/Olyakaya/task_gitops.git
    targetRevision: HEAD
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Replace=true
