apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      annotations:
        rollme: { { randAlphaNum 5 | quote } }
      labels:
        app: myapp
    spec:
      nodeSelector:
        agentpool: workloadpool
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: myapp
          image: task10cr.azurecr.io/myapp:v1
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: myapp-config
