apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: myapp
    behavior: replace # This ensures it replaces any existing ConfigMap
    literals:
      - GREETING_MESSAGE=Hello, Azure! deploy by Argo
